读入图像  
使用函数cv2.imread(filepath,flags)读入一副图片  
filepath：要读入图片的完整路径
flags：读入图片的标志  
---cv2.IMREAD_COLOR：默认参数，读入一副彩色图片，忽略alpha通道  
---cv2.IMREAD_GRAYSCALE：读入灰度图片  
---cv2.IMREAD_UNCHANGED：顾名思义，读入完整图片，包括alpha通道  
显示图像  
使用函数cv2.imshow(wname,img)显示图像，第一个参数是显示图像的窗口的名字，第二个参数是要显示的图像（imread读入的图像），窗口大小自动调整为图片大小  
保存图像  
使用函数cv2.imwrite(file，img，num)保存一个图像。第一个参数是要保存的文件名，第二个参数是要保存的图像。

In [1]:
import numpy as np
import cv2


img = cv2.imread('imori.jpg')

cv2.imshow('image',img)
k = cv2.waitKey(0)
if k== 27:
    cv2.destroyAllWindows()
elif k == ord('s'):
    cv2.imwrite('color.jpg',img)
    cv2.destroyAllWindows()

2.1 基本I/O脚本  
读写图像文件  
用numpy和python 表示一幅图像的细节  
img.shape #返回行列，如果超过一个通道会返回通道数

In [2]:
import numpy as np
import cv2
img = np.zeros((3,3), dtype=np.uint8)#黑色的正方形图像
print(img,img.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)


灰度图-RGB图相互转换  
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)    # BGR转灰度  
img_bgr = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2BGR)    # 灰度转BRG  
img_rgb = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2RGB)    # 也可以灰度转RGB

In [3]:
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
cv2.imwrite('black.jpg',img)  #保存下来，只有小小的黑色方块
print(img,img.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] (3, 3, 3)


读取图片，保存成另外的格式

In [4]:
img = cv2.imread('imori.jpg')
cv2.imwrite('img.png',img)

True

 imread()函数的参数:  
 IMREAD_ANYCOLOR = 4  
 IMREAD_ANYDEPATH = 2  
 IMREAD_COLOR = 1  
 IMREAD_GRAYSCALE = 0  
 IMREAD_LOAD_GDAL = 8    
 IMREAD_UNCHANGED = -1
 

In [5]:
#h灰度读入，保存
grayimg = cv2.imread('img.png',cv2.IMREAD_GRAYSCALE)
cv2.imwrite('gray.png',grayimg)

True

图像与原始字节之间的转换  
  
一个OpenCV图像一般是numpy.array类型的二维或者三维数组。8位的灰度图像是一个含有字节值的二维数组，维度为 height x width，24位的BGR是一个三维数组 维度为[ height, width, channel ]

In [12]:
img = cv2.imread('imori.jpg')
print('图像{}的纬度是{}'.format('img',img.shape))
#显示转换为标准的一维python bytearray格式
byte_array = bytearray(img)
print('转换之后的图像的纬度是{}',len(byte_array),type(byte_array))

#bytearray含有恰当顺序的字节，可以通过显示转换和重构 得到numpy.array形式的图像
img2 = np.array(byte_array).reshape(936,1248,3)
cv2.imwrite('reshape.jpg',img2)

图像img的纬度是(936, 1248, 3)
转换之后的图像的纬度是{} 3504384 <class 'bytearray'>


True

In [15]:
'''
一个详细的例子 将含有随机字节的bytearray转换为灰度图像和BGR图像
'''
import cv2
import numpy
import os
#随机生成120000个字节的数组
random_byte_array = bytearray(os.urandom(120000))
#转换成numpy.array类型
byte_array = np.asarray(random_byte_array,dtype = numpy.uint8)
#把数组转换成 400* 300的灰度图像
gray_image = byte_array.reshape(400,300)
cv2.imwrite('test_gray.png',gray_image)
#把数组转换成400*100的BGR图像
bgr_image = byte_array.reshape(100,400,3)
cv2.imwrite('test_bgr.png',bgr_image)
#运行后随机生成两个图片，可以观察

True

使用numpy.array访问图像数据

In [25]:
#将BGR图像在(0,0)处的像素转化为白像素
img = cv2.imread('imori.jpg')
print(img[0,0])
img[0,0] = [255,255,255]
cv2.imwrite('white_point.jpg',img)

#numpy.array的item(n_hight,n_width,n_channel)方法可以获取指定索引的值  通道BGR依次对应索引0,1,2

print(img.item(100,200,0))#获取100行200列B通道的值
img.itemset((100,200,0), 255)#设置新值
print(img.item(100,200,0),'\n------')

#将指定通道的所有值置0
img[:,:,1] = 1
cv2.imwrite('no_green.jpg',img)#打开路径下的图片观察一下

#设定感兴趣的区域（Region Of Interest，ROI）
#将该区域与变量绑定，设定第二个区域，并将第一个区域的值分配给第二个区域
#（(将图像一部分拷贝到图像另一部分)）
img = cv2.imread('imori.jpg')
roi = img[100:300,300:500]
img[300:500,100:300] = roi
cv2.imwrite('roi_test.jpg',img)
#图像的高度，宽度，和通道数   图像的大小  图像的数据类型
print(img.shape,img.size,img.dtype)



[189 159 188]
33
255 
------
(936, 1248, 3) 3504384 uint8


视频文件的读/写  
OpenCV提供了VideoCapture类和VideoWriter类来支持各种格式的视频文件。支持的格式类型会因系统的不同而变化，但是都支持avi格式，在到达视频文件末尾之前，VideoCapture可通过read()函数来获取新的帧，每一帧都是一幅基于BGR的图像。VideoWriter可以通过write()写入每一帧图像。

In [8]:
import cv2
video_capture = cv2.VideoCapture('test_video.mp4')
#获取帧速率
fps = video_capture.get(cv2.CAP_PROP_FPS)
print('该视频的帧速率为：',fps)

#获取图片的宽和高
size = (int(video_capture.get(cv2.CAP_PROP_FRAME_WIDTH)),int(video_capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
print('该视频每一帧的大小为：',size)

#1VideoWriter类的构造函数指定视频文件名，这个文件名对应的文件若存在，则会被覆盖
#2需要指定编解码器  3帧速率  4帧大小
video_writer = cv2.VideoWriter('myoutputvid.avi',cv2.VideoWriter_fourcc('m','p','4','v'),fps,size)
success,frame = video_capture.read()
cv2.imwrite('frame.jpg',frame)
#读取帧，知道没有帧可以读取
while success:
    video_writer.write(frame)
    sucess,frame = video_capture.read()
video_writer.release()
video_capture.release()
print('结束')

该视频的帧速率为： 30.0
该视频每一帧的大小为： (1920, 1080)


KeyboardInterrupt: 

---------------  
捕获摄像头的帧,并保存视频文件  

VedioCapture类可以获得摄像头的帧流，但对于摄像头而言，通常不是用视频的文件名来构造VideoCapture类， 而是需要传递摄像头的设备索引(device index)，VideoCapture类对象的get方法不能返回摄像头帧速率的准确值，它总是返回0。

In [7]:
#获取摄像头10s的视频信息，并将其写入一个avi文件中
#(用其他ide运行看结果会比较好)
import cv2
camera_capture = cv2.VideoCapture(0)
fps = 30
size = (int(camera_capture.get(cv2.CAP_PROP_FRAME_WIDTH)),int(camera_capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))

video_writer = cv2.VideoWriter('camera.mp4',cv2.VideoWriter_fourcc('m','p','4','v'),fps,size)
success,frame = camera_capture.read()
num_frame_remaining = 10*fps -1   #当前剩余捕获图片个数
while success and num_frame_remaining >0 :
    #写入一帧
    video_writer.write(frame)
    #读取一帧
    success,frame = camera_capture.read()
    num_frame_remaining -= 1
camera_capture.release()
video_writer.release()

在窗口显示图像  
imshow()函数可以用来实现图片，但是这个图片显示出来后会立即消失，一般我们需要使用waitKey()函数,
传入等待键盘触发的时间，单位为ms，返回值为-1(表示没有键按下)或者ASCII码。并且需要调用destoryAllWindows()
释放OpenCV创建的所有窗口

In [9]:
import cv2
import numpy as np
img = cv2.imread('imori.jpg')
cv2.imshow('my image',img)
cv2.waitKey(10)
cv2.destroyAllWindows()

在窗口显示摄像头帧  
nameWindow()、imshow()、DestroyWindow()函数允许通过指定窗口名来创建、显示和销毁窗口。  


In [8]:
import cv2

clicked = False
def on_mouse(event, x, y, flags, param):
    '''
    #鼠标事件的回调函数
    
    args:
        event:回调事件参数，有很多取值，分别对应不同的鼠标事件
        param:可选参数，它是setMouseCallback()函数的第三个参数 默认为0
        flag：标志参数 如 cv2.EVENT_FLAG_LBUTTON：该事件对应按下鼠标左键
        x,y：鼠标坐标
    '''
    global clicked
    #左键松开
    if event == cv2.EVENT_LBUTTONUP:
        clicked = True
camera_capture = cv2.VideoCapture(0)
#指定窗口名来创建窗口
cv2.namedWindow('mywindow')
#设置鼠标事件回调函数，来获取鼠标输入
cv2.setMouseCallback('mywindow',on_mouse)
print('Showing camera feed.Click window or press any key to stop')
success,frame = camera_capture.read()
#OpenCV窗口只有在调用cv2.waitKey()函数时才会更新，并且waitKey()函数只有在OpenCV窗口成为活动窗口时，才能捕获输入信息
while success and cv2.waitKey(1) == -1 and not clicked:
    cv2.imshow('mywindow',frame)
    success,frame = camera_capture.read()


cv2.destroyWindow('mywindow')      #销毁所有窗口

camera_capture.release()


Showing camera feed.Click window or press any key to stop
